name: Auto Post Mail

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * * "
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.x
      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install BeautifulSoup4
          pip install datetime
          pip install PyGithub
          pip install pyyaml
          pip install python-dotenv 
      - name: run
        env:
          EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}
          EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
        run: python main.py
